export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const HOTELS_LOADED = 'HOTELS_LOADED';
export const HOTEL_SELECTED = 'HOTEL_SELECTED';

export const VEHICLES_LOADED = 'VEHICLES_LOADED';
export const VEHICLE_SELECTED = 'VEHICLE_SELECTED';

export const CITIES_LOADED = 'CITIES_LOADED';
export const ORIGIN_SELECTED = 'ORIGIN_SELECTED';
export const DESTINATION_SELECTED = 'DESTINATION_SELECTED';

export const ITENARIES_LOADED = 'ITENARIES_LOADED';
export const ITENARY_ADDED = 'ITENARY_ADDED';
export const ITENARY_FILTERED = 'ITENARY_FILTERED';
export const USER_ITENARIES_LOADED = 'USER_ITENARIES_LOADED';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const DAYS_ALLOCATED = 'DAYS_ALLOCATED';
export const TRAVEL_TIME_SET = 'TRAVEL_TIME_SET';